INSERT INTO produto (nome, preco, quantidade) VALUES
                                                  ('Notebook Lenovo IdeaPad 3', 2899.90, 15),
                                                  ('Mouse Logitech M185', 79.90, 50),
                                                  ('Teclado Mecânico Redragon', 249.90, 30),
                                                  ('Monitor LG 24', 899.90, 20),
                                                  ('Headset HyperX Cloud II', 499.90, 12),
                                                  ('Webcam Logitech C920', 429.90, 0),
                                                  ('SSD Kingston 480GB', 299.90, 25),
                                                  ('Memória RAM Kingston 8GB', 159.90, 40),
                                                  ('HD Externo Seagate 1TB', 349.90, 22),
                                                  ('Pen Drive SanDisk 64GB', 49.90, 100),
                                                  ('Cabo HDMI 2.0', 39.90, 75),
                                                  ('Carregador USB-C 65W', 129.90, 35),
                                                  ('Adaptador USB Wi-Fi', 89.90, 28),
                                                  ('Caixa de Som JBL Go 3', 299.90, 16),
                                                  ('Mousepad Gamer RGB', 119.90, 27),
                                                  ('Cadeira Gamer', 1299.90, 10),
                                                  ('Suporte para Notebook', 99.90, 32),
                                                  ('Hub USB 3.0', 69.90, 45),
                                                  ('Fonte ATX 550W', 329.90, 14),
                                                  ('Placa de Vídeo RTX 4060', 1899.90, 8);