server:
  port: 8400
spring:
  application:
    name: historico-pedidos-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers:
      - ${KAFKA_URL}
#eureka:
#  client:
#    enabled: true
#    service-url:
#      #defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true