server:
  port: 8200
spring:
  application:
    name: usuarios-api
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: ${keycloack_url}
          jwk-set-uri: ${JWK_URI}
keycloack:
  host: ${keycloack_host}
  realmMaster: ${keycloack_master_realm}
  realm: ${client_realm}
  username: ${keycloack_username}
  password: ${keycloack_password}
  clientId: ${client_id}
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${eureka_url}
    fetch-registry: true
    register-with-eureka: true