server:
  port: 8100

spring:
  application:
    name: pedidos-api
  datasource:
    url: ${DB_URL}


    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI}
  kafka:
    bootstrap-servers:
      - ${KAFKA_URL}
keycloack:
  clientId: ${CLIENT_ID}
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true
